### ISSUE TITLE
Creating a request

### ISSUE THREAD

**Issue by mikeKane** [square/connect-javascript-sdk#28]
Im trying to create a request but failing for the money field. The docs are a little confusing as the naming conventions do not seem to be right. Can anyone help me with an example?

here is what I have 

`var SquareConnect = require('square-connect');
  var defaultClient = SquareConnect.ApiClient.instance;

  // Configure OAuth2 access token for authorization: oauth2
  var oauth2 = defaultClient.authentications['oauth2'];
  oauth2.accessToken = 'sandbox--TOKEN';

  var apiInstance = new SquareConnect.TransactionsApi();
  var money = new SquareConnect.Money();
  money.amount_money = 100;
  money.currency = "USD";

  var locationId = "PB7DD187ZCTCB"; // String | The ID of the location to associate the created transaction with.

  var body = new SquareConnect.ChargeRequest(); // ChargeRequest | An object containing the fields to POST for the request.  See the corresponding object definition for field details.
  body.idempotency_key = "YTHDGJIK";
  body.amount_money = money;;
  body.currency = "USD";
  body.cardNonce = "CBASECXnYKA9fd8KXid_9sKAHukgAF";
  body["referenceId"] = "Confirmation purchase";
  body["note"] = "Thank you for your purchase";
apiInstance.charge(locationId, body).then(function(data) {
    console.log('API called successfully. Returned data: ' + data);
  }, function(error) {
    console.error(error);
  });
`

**Comment by StephenJosey** [comment]
`SquareConnect.Money()` has two properties: `amount` and `currency` (https://github.com/square/connect-javascript-sdk/blob/master/docs/Money.md). Change your code to use do:
```
var money = new SquareConnect.Money();
money.amount = 100;
money.currency = "USD";
```

Also, `SquareConnect.ChargeRequest()` does not have a `currency` field, so there's no need to set that (remove `body.currency = "USD";`). Please let me know if that doesn't work for you.

**Comment by mikeKane** [comment]
Thank you for your reply

That did seem to clear up that error. I am now receiving `text: '{"errors":[{"category":"INVALID_REQUEST_ERROR","code":"NOT_FOUND","detail":"Card nonce not found in this `production` application environment. Please ensure an application ID belonging to the same environment is used for the SqPaymentForm."}]}`

The payment form has a var inside of the .js named applicationId and I set that to the production key from me dashboard and then in the node code as stated above I use the personal Access Token from my production account but that doesn't seem to be syncing up. Im testing with my own CC at the moment

**Comment by StephenJosey** [comment]
That sounds correct (although in the code you said you were using sandbox, not production). Are you using the new card nonce each time? In the code you provided originally it was hardcoded, so just want to double-check.

**Comment by mikeKane** [comment]
It turned out I needed to clear the cache after the deploy on the production payment form. 

Thank you sincerely. One last question I promise. I am trying to get multiparty transactions set up and I have this code, but I don't see the money being split. 

` var SquareConnect = require('square-connect');
  var defaultClient = SquareConnect.ApiClient.instance;

  // Configure OAuth2 access token for authorization: oauth2
  var oauth2 = defaultClient.authentications['oauth2'];
  oauth2.accessToken = 'sq0uip-7UI9-eMTC9m0bNFZAdZBA';

  var apiInstance = new SquareConnect.TransactionsApi();

  var money = new SquareConnect.Money();
  money.amount = 250;
  money.currency = "USD";

  var locationId = "PB7DD163ZCZZZ"; // String | The ID of the location to associate the created transaction with.

  var body = new SquareConnect.ChargeRequest(); // ChargeRequest | An object containing the fields to POST for the request.  See the corresponding object definition for field details.
  body.idempotency_key = "IUJZSDSLS";
  body.amount_money = money;
  body.card_nonce = "CBASEPEWoIOOPPMpg5s471AGHSYHD";
  body.reference_ID = "Confirmation from Mike";
  body.note = "Thank you for your purchase";

  var recipients = new SquareConnect.AdditionalRecipient();
  recipients.locationId = "0ZZZZ02Y0ZZZZ";
  recipients.description = "FoodTruckIt Split";

  var recipientMoney = new SquareConnect.Money();
  recipientMoney.amount = 60;
  recipientMoney.currency = "USD";
  recipients.amount_money = recipientMoney;

  body.additional_recipient = [recipients];

  apiInstance.charge(locationId, body).then(function(data) {
    console.log('API called successfully. Returned data: ' + data);
  }, function(error) {
    console.error(error);
  }); `

**Comment by mikeKane** [comment]
```ar SquareConnect = require('square-connect');
  var defaultClient = SquareConnect.ApiClient.instance;

  // Configure OAuth2 access token for authorization: oauth2
  var oauth2 = defaultClient.authentications['oauth2'];
  oauth2.accessToken = "token'; //Token of the merchant

  var apiInstance = new SquareConnect.TransactionsApi();

  var money = new SquareConnect.Money();
  money.amount = 150;
  money.currency = "USD";

  var locationId = "location_id"; // location id of the merchant

  var body = new SquareConnect.ChargeRequest();
  body.amount_money = money;
  body.card_nonce = "nonce";
  body.reference_ID = "Confirmation";
  body.note = "Thank you for your purchase";

  var recipient = new SquareConnect.AdditionalRecipient();
  recipient.location_id = "location_id"; //App's location id - merchant pays a fee
  recipient.description = "Split";

  var recipientMoney = new SquareConnect.Money();
  recipientMoney.amount = 60;
  recipientMoney.currency = "USD";
  recipient.amount_money = recipientMoney;

  body.additional_recipients = [recipient];

  apiInstance.charge(locationId, body).then(function(data) {
    console.log('API called successfully. Returned data: ' + data);
  }, function(error) {
    console.error(error);
  });```

**Comment by StephenJosey** [comment]
In order for multiparty transactions to work, you will need to be calling `Charge` from the other merchant (ie the one you're wanting to take a fee from - using their OAuth access token). In the `additional_recipients` field, you will use your app's `location_id` to receive the fee. Note that you will need to use `OAuth` in order to accomplish this.
