### ISSUE TITLE
How to get item's images?

### ISSUE THREAD

**Issue by ezetaraborelli** [square/connect-javascript-sdk#50]
Hi! Since last API update (2019-03-27), I'm not able to get the item's images, I see the image_id field on each item, but there is no explanation on the docs on how to retrieve the image url from there.
Is it explained somewhere I couldn't find?

Thanks!

**Comment by StephenJosey** [comment]
It should have a `url` field on the `V1ItemImage`. Are you not able to see it?
https://github.com/square/connect-javascript-sdk/blob/master/docs/V1ItemImage.md

**Comment by ezetaraborelli** [comment]
When I get the items from searchCatalogObjects(), I only get a field like this on each  item

`"image_id": "EGBOIBGPQC3NHO3G44XY6QQT"`

I tried creating a new V1ItemImage (doing `SquareConnect.V1ItemImage.constructFromObject({id: imageId})`) hoping that it will automatically generate the url, it only returned the same ID I provided.
Am I missing something  here? (I had to take on a legacy project that had most of the square integration already done, so I'm not too proficient with this API yet)

**Comment by StephenJosey** [comment]
There is no way to create an image using the SDK. You'll need to build your own HTTP request and call the `UploadItemImage` endpoint: https://docs.connect.squareup.com/api/connect/v2#endpoint-v1items-uploaditemimage

**Comment by ezetaraborelli** [comment]
Mmm sorry, I think I  didn't explained myself correctly. The items already have an image uploaded (from the web), and I'm trying to get that image to show on an app I'm developing. I only need to get the image url from somewhere in order to send it to the app. In the previous version I was using, the API returned a image_url for each item, but no more, now only the image_id is returned

**Comment by StephenJosey** [comment]
Sorry that I misunderstand. You can use the `image_id` to pass to the `RetrieveCatalogObject` endpoint to retrieve the `CatalogImage` object which contains the url.

**Comment by yuvalt** [comment]
It used to be part of the item. There was an image_url. Currently there is only image_id. Making another call for each item just to retrieve the URL doesn't makes sense, especially since CatalogObject holds image_data.

**Comment by ryho** [comment]
The image is now a separate catalog object type, like the Category. Instead of fetching the image with another RPC, you can set `include_related_objects` to fetch the image along with the item. For the list endpoint you can specify ITEM_IMAGE as one of the object types to fetch the images as well.

**Comment by yuvalt** [comment]
Thank you, it's working. I specified IMAGE (not ITEM_IMAGE) and got the image information.

**Comment by ezetaraborelli** [comment]
> Thank you, it's working. I specified IMAGE (not ITEM_IMAGE) and got the image information.

This made it. Thank you all for your help!!

Ps, sorry for the delay, a more urgent task showed up so I had to put this on stand by
